version: '3.8'
services:
  jenkins-master:
    build: ./jenkins-master
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000" # Port for agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/login"]
      interval: 10s
      retries: 5
      timeout: 10s

  nodejs-slave:
    build: ./nodejs-slave
    # privileged: true
    # user: root
    # ulimits:
    #   nofile: 1024
    container_name: nodejs-slave
    ports:
      - "3000:3000"
    networks:
      - jenkins-network
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JNLP_URL=http://jenkins-master:8080/computer/nodejs-slave/jenkins-agent.jnlp
      - SECRET=c33c320acde294e84c2fdf3db060fcaf35e38cd3d08ef74967636a570d632b9e
      - SLAVE_NAME=nodejs-slave
    depends_on:
      jenkins-master:
        condition: service_healthy
        restart: true

  java-slave:
    build: ./java-slave
    container_name: java-slave
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JNLP_URL=http://jenkins-master:8080/computer/java-slave/jenkins-agent.jnlp
      - SECRET=231a13368494acb12cee03efe6ab2e14e7b3cfcac988c13125abe0ea464c4936
      - SLAVE_NAME=java-slave
    depends_on:
      jenkins-master:
        condition: service_healthy
        restart: true

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
