version: '3.8'
services:
  jenkins-master:
    build: ./jenkins-master
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000" # Port for agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/login"]
      interval: 10s
      retries: 5
      timeout: 10s

  nodejs-slave:
    build: ./nodejs-slave
    # privileged: true
    # ulimits:
      # nofile: 1024
    container_name: nodejs-slave
    # ports:
    #   - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JNLP_URL=http://jenkins-master:8080/computer/nodejs-slave/jenkins-agent.jnlp
      - SECRET=4e28eb11d47d3f345b90d12a879b8b8c1de576c69e98274c3ea45a9b192bb616
      - SLAVE_NAME=nodejs-slave
    depends_on:
      jenkins-master:
        condition: service_healthy
        restart: true

  java-slave:
    build: ./java-slave
    container_name: java-slave
    privileged: true
    ulimits:
      nofile: 1024
    ports:
      - "3001:3001"
    networks:
      - jenkins-network
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JNLP_URL=http://jenkins-master:8080/computer/java-slave/jenkins-agent.jnlp
      - SECRET=4727eac17510be3b4f75485b326c2aeb2f087af07f67a1c7addcd15a1033a91f
      - SLAVE_NAME=java-slave
    depends_on:
      jenkins-master:
        condition: service_healthy
        restart: true

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
