pipeline {
    agent {
        label 'java-slave'
    }
    environment {
        APP_PORT = '3001'
        JAR_NAME = 'hello-world-spring-1.0.0.jar'
    }
    stages {
        stage('Verify Tools') {
            steps {
                sh '''
                    java -version
                    mvn -version
                '''
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('spring-boot-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('spring-boot-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('spring-boot-app') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('Deploy') {  
            steps {  
                // sh '''
                //     chmod +x run.sh
                // '''
                // sh '''
                //     ./run.sh
                // '''
                dir('spring-boot-app') {
                sh '''  
                    echo "Current user: $(whoami)"  
                    echo "Current directory: $(pwd)"  
                    echo "Initial permissions:"  
                    ls -la  
                    
                    nohup java -jar target/hello-world-spring-1.0.0.jar --server.port=3001 \\> app.log 2\\>\\&1 \\&  
                    echo "Application started with PID: $!"  
                    sleep 5  
                    ps aux | grep hello-world-spring-1.0.0.jar
                    cat app.log  
                '''  
                }

            }  
        }  
    }
}