pipeline {
    agent {
        label 'java-slave'
    }
    environment {
        APP_PORT = '3001'
        JAR_NAME = 'hello-world-spring-1.0.0.jar'
    }
    stages {
        stage('Verify Tools') {
            steps {
                sh '''
                    java -version
                    mvn -version
                '''
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('spring-boot-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('spring-boot-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('spring-boot-app') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('Deploy') {  
            steps {  
                sh '''
                    chmod +x run.sh
                '''
                sh '''
                    ./run.sh
                '''
            }  
        }  
    }
}